TARGET:
  PROBLEM_TYPE: classification # regression / classification
  CLASSIFICATION_TYPE: multiclass # null / binary / multiclass
  NAME: target_variable_name # as it appears in the originaldataset
  ORDER: [] # ["value1", "value2", "value3", ...]

COLUMNS:
  RENAME: {} # {"old_name": "new_name", "old_name2": "new_name2", ...}
  DROP: [] # ["column_name1", "column_name2", "column_name3", ...]
  DROP_AFTER_TRANSFORMATIONS: [] # ["column_name1", "column_name2", "column_name3", ...]

CLEANING:
  REPLACE_BY_NAN: [] # ["value1", "value2", "value3", ...]
  REPLACE_MAP: {} # {"old_value": "new_value", "old_value2": "new_value2", ...}
  REPLACE_IN_SPECIFIC_COLUMNS: {} # {"column_name": {"old_value": "new_value", "old_value2": "new_value2", ...}, "column_name2": {"old_value": "new_value", "old_value2": "new_value2", ...}, ...}
  TYPE_CONVERSION: {} # {"column_name": "type", "column_name2": "type2", ...}
  IMPUTATION:
    {} # column names should be the new names (lowercase and spaces replaced by _)
    # <column_name1>: drop # drop / mean / median / mode / (pour constant, mettre directementla valeur à la place)
    # <column_name2>: drop # drop / mean / median / mode / (pour constant, mettre directementla valeur à la place)
  OUTLIERS: {} # {"column_name": "strategy", "column_name2": "strategy2", ...}

ENCODING:
  ORDINAL: {} # {"column_name": ["value1", "value2", "value3", ...], "column_name2": ["value1", "value2", "value3", ...], ...}

IMBALANCE:
  STRATEGY: # Laisser vide pour null, smote / smotenc / random_over / random_under

DIMENSIONALITY_REDUCTION:
  STRATEGY: # Laisser vide pour null ou mettre null, select_k_best / pca / tsvd
  # Only one of the following values should be non null:
  K_BEST_FEATURES: # 50
  PCA_COMPONENTS: # 0.95
  TSVD_COMPONENTS: # 0.95

TRAINING:
  MODELS:
    REGRESSION:
      XGBREGRESSOR: 1
      LGBMREGRESSOR: 1
      RANDOMFORESTREGRESSOR: 1
      LINEARREGRESSION: 1
      RIDGE: 0
      LASSO: 0
      SVR: 1
      DECISIONTREEREGRESSOR: 0
    CLASSIFICATION:
      XGBCLASSIFIER: 1
      LOGISTICREGRESSION: 1
      LGBMCLASSIFIER: 0
      CATBOOSTCLASSIFIER: 1
      RANDOMFORESTCLASSIFIER: 0
      SVC: 0
      GRADIENTBOOSTINGCLASSIFIER: 0
      KNEIGHBORSCLASSIFIER: 0
      DECISIONTREECLASSIFIER: 0
      NAIVEBAYESCLASSIFIER: 0
  GRIDSEARCH: True
  PARAM_GRIDS:
    REGRESSION:
      XGBREGRESSOR:
        n_estimators: [100, 200]
        learning_rate: [0.01, 0.1]
        max_depth: [3, 6]
      LGBMREGRESSOR:
        n_estimators: [100, 200]
        learning_rate: [0.01, 0.1]
        num_leaves: [31, 63]
      RANDOMFORESTREGRESSOR:
        n_estimators: [50, 100]
        max_depth: [10, 20]
        min_samples_split: [2, 5]
      LINEARREGRESSION:
        fit_intercept: [true, false]
      RIDGE:
        alpha: [0.1, 1.0, 10.0]
      LASSO:
        alpha: [0.001, 0.01, 0.1]
      SVR:
        C: [0.1, 1, 10]
        kernel: ["linear", "rbf"]
      DECISIONTREEREGRESSOR:
        max_depth: [None, 5, 10]
        min_samples_split: [2, 5]
    CLASSIFICATION:
      XGBCLASSIFIER:
        n_estimators: [100, 200]
        learning_rate: [0.01, 0.1]
        max_depth: [3, 6]
      LOGISTICREGRESSION:
        C: [0.1, 1, 10]
        penalty: ["l2"]
        solver: ["lbfgs"]
      LGBMCLASSIFIER:
        n_estimators: [100, 200]
        learning_rate: [0.01, 0.1]
        num_leaves: [31, 63]
      CATBOOSTCLASSIFIER:
        iterations: [100, 200]
        depth: [4, 6]
        learning_rate: [0.01, 0.1]
      RANDOMFORESTCLASSIFIER:
        n_estimators: [50, 100]
        max_depth: [10, 20]
        min_samples_split: [2, 5]
      SVC:
        C: [0.1, 1, 10]
        kernel: ["linear", "rbf"]
      GRADIENTBOOSTINGCLASSIFIER:
        n_estimators: [100, 200]
        learning_rate: [0.01, 0.1]
        max_depth: [3, 5]
      KNEIGHBORSCLASSIFIER:
        n_neighbors: [3, 5, 7]
        weights: ["uniform", "distance"]
      DECISIONTREECLASSIFIER:
        max_depth: [None, 5, 10]
        min_samples_split: [2, 5]
      NAIVEBAYESCLASSIFIER:
        var_smoothing: [1e-09, 1e-08, 1e-07]
  CROSS_VALIDATION: True
  N_FOLDS: 5
  SAVE_RESULTS_TO_CSV: True # True / False
  LOG_IN_MLFLOW: True # True / False